services:
  eurekaserver:
    build: ./eurekaserver
    ports:
      - "8761:8761"

  apigateway:
    build: ./apigateway
    ports:
      - "8080:8080"
    depends_on:
      - eurekaserver

  productservice:
    build: ./productservice
    ports:
      - "8081:8081"
    depends_on:
      - eurekaserver

  orderservice:
    build: ./orderservice
    ports:
      - "8082:8082"
    depends_on:
      - eurekaserver

  inventoryservice:
    build: ./inventoryservice
    ports:
      - "8083:8083"
    depends_on:
      - eurekaserver